### ISSUE TITLE
Add datasets in a directory called "datasets"

### ISSUE THREAD

**Issue by sdotpeng** [nalmadi/EMIP-Toolkit#13]
Initially, there was only `EMIP` dataset. After we added some dataset from Eye Link 1000, we found out that the organization of each dataset is different. We now want to add datasets in one directory called "datasets", and we will separate each into a folder. 

In future development, we will write up instructions for importing dataset.

**Comment by nalmadi** [comment]
I added a directory and one data set (the EyeLink 1000 one) and I will add EMIP data later.
