### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by nalmadi** [nalmadi/EMIP-Toolkit#18]
So far we have been using the example notebooks as tests, but it would be much better to develop unit tests for every method in the toolkit.  Maybe consider automating the testing process on GitHub to make collaboration and onboarding easier.

**Comment by quanphan2906** [comment]
In the latest version, every public function has its own unit test now. We have also added github workflow to automate the testing process whenever there is a pull request or a push. Closing this issue.
