### ISSUE TITLE
draw_trial method - How to paste an image with a transparent background onto a larger black background image

### ISSUE THREAD

**Issue by quanphan2906** [nalmadi/EMIP-Toolkit#26]
In the draw_trial method of the Trial class:

https://github.com/nalmadi/EMIP-Toolkit/blob/bac781b17e718207e4c39e900c55ba584fdf3d40/emip_toolkit.py#L593-L674

This line of code pastes an image in the AlMadi 2018 runtime dataset (an image with white text and transparent background), hereafter referred to as "the image", into a black background, hereafter referred to as "this feature": 

https://github.com/nalmadi/EMIP-Toolkit/blob/bac781b17e718207e4c39e900c55ba584fdf3d40/emip_toolkit.py#L631

**1st Question**: How does converting the image into RGBA and using it as a mask image manage to achieve this feature?

My expectation is that to achieve this feature, we only need to paste the image on top of the black background without having to use any mask image:

```
background.paste(im.convert('RGBA'), trial_location)
```

Because the background of the image is already transparent, and the word is white, contrast with the black background. However, what I get is a completely white box on a black background:

![result](https://user-images.githubusercontent.com/52489089/139466660-78ba1fdb-6f0c-463b-9d3f-a78ec49cfcb9.png)

**2nd Question**: Why the line of code I wrote fail to achieve this feature?

Here is full code I used to test both ways:

```
    image_path = "EMIP-Toolkit/datasets/AlMadi2018/runtime/images/5667346413132987794.png"
    im = Image.open(image_path)

    background_size = (1024, 768)
    background = Image.new( 'RGBA', background_size, color='black' )

    trial_location = (10, 375)

    # background.paste( im, trial_location, im.convert('RGBA') )
    background.paste( im.convert('RGBA'), trial_location )
    background.save("result.png")
    
    im = background.copy()
    im.show()
```

**Comment by sdotpeng** [comment]
Hi Quan, 

Thank you for the question! I will get back to it tomorrow.

**Comment by quanphan2906** [comment]
This question should be directed to forums on Python Pillow library instead of here. Closing this issue as it is irrelevant to emtk
