### ISSUE TITLE
(Bug) In the Jupyter notebook for the the Eyelink1000

### ISSUE THREAD

**Issue by TheWeisGuy** [nalmadi/EMIP-Toolkit#48]
im = EMIP[subject_ID].trial[trial_num].draw_trial(image_path, draw_raw_data=False, draw_fixation=True, draw_saccade=False, draw_number=True, draw_aoi=True)

When draw_saccade is set to true it gives an error claiming a font is missing

**Comment by sdotpeng** [comment]
Hi,

I believe the font needs to be under the resource folder.

**Comment by nalmadi** [comment]
Thanks @sdotpeng, which resource folder?

**Comment by sdotpeng** [comment]
I think that folder was removed. Should I pull the latest, add the font, and make another pull request?

**Comment by nalmadi** [comment]
We arranged the datasets into zip files, do you want to add the font to the zip file of AlMadi2018 dataset?  Do you think that would work?

Thank you!

**Comment by sdotpeng** [comment]
Sure! I will do that!

**Comment by nalmadi** [comment]
Thank you!  Let's test this by running the EyeLink1000 Jupyter notebook with draw_saccade = True

**Comment by quanphan2906** [comment]
With the latest version, `draw_trial` uses the default font, so there is no need to add external font.
