### ISSUE TITLE
Samples variable hold fixations, saccades, and blinks instead of raw samples in Al Madi 2018 dataset

### ISSUE THREAD

**Issue by quanphan2906** [nalmadi/EMIP-Toolkit#73]
In the ```read_EyeLink1000``` function, fixations, saccades, and blinks were parsed into the ```samples``` variable. An example can be seen below:
https://github.com/nalmadi/EMIP-Toolkit/blob/d1a7eabd08ca27c062b5f14118395eaea8d5eac2/emip_toolkit.py#L918-L934

The same token that is used to populate the fields of the ```Fixation``` object was also appended into ```samples```. If the Al Madi 2018 dataset does not have raw samples, the ```samples``` variable should be kept empty to avoid any confusion.

**Comment by nalmadi** [comment]
I agree!  Good catch.

**Comment by quanphan2906** [comment]
The `samples` from the AlMadi dataset is now an empty dataframe. Kindly refer to the updated notebook: https://github.com/nalmadi/EMIP-Toolkit/blob/main/AlMadi.ipynb
