### ISSUE TITLE
not using the variable "sample_duration"

### ISSUE THREAD

**Issue by haowenmvp** [nalmadi/EMIP-Toolkit#77]
At line 69 of idt_classifier.py, it should be 
[timestamp, len(window_x) * sample_duration, statistics.mean(window_x), statistics.mean(window_y)])
not
[timestamp, len(window_x) * 4, statistics.mean(window_x), statistics.mean(window_y)])

**Comment by nalmadi** [comment]
That makes sense, thanks!
Do you want to make a pull request with that enhancement?

**Comment by nalmadi** [comment]
Awesome, thanks!
